name: smart_yoga_mat
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version information
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_reactive_ble: ^5.3.1  # BLE library
  permission_handler: ^11.3.1
  get_storage: ^2.1.1
  #weather: ^3.1.1
  flutter_blue_plus: ^1.34.5
  #flutter_blue: ^0.8.0
  
    # Classic Bluetooth library
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Linting support

flutter:
  uses-material-design: true
  #assets:
   # - assets/  # Add your asset directory here if any (optional)

# iOS-specific configuration for permissions
ios:
  deployment_target: '12.0'
  
  plugin:
    platforms:
      ios:
        package: flutter_bluetooth_serial
        plugin_class: BluetoothSerialPlugin
